import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export async function POST(req: Request) {
  try {
    // FIX: Destructure the computed sections directly from the request payload
    const { answers, verdict, sections } = await req.json();

    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

    let page = pdf.addPage();
    const { width, height } = page.getSize();

    const margin = 50;
    let y = height - margin;
    const lineHeight = 16;

    // --------------------------
    // Simple safe word wrapping
    // --------------------------
    const wrap = (text: string, maxChars = 90) => {
      const words = text.split(' ');
      const lines: string[] = [];
      let current = '';

      words.forEach((word) => {
        if ((current + word).length > maxChars) {
          lines.push(current.trim());
          current = word + ' ';
        } else {
          current += word + ' ';
        }
      });

      if (current) lines.push(current.trim());
      return lines;
    };

    const draw = (
      text: string,
      size = 12,
      bold = false,
      color = rgb(0, 0, 0)
    ) => {
      const lines = wrap(text);

      lines.forEach((line) => {
        if (y < margin + 40) {
          page = pdf.addPage();
          y = height - margin;
        }

        page.drawText(line, {
          x: margin,
          y,
          size,
          font: bold ? boldFont : font,
          color,
        });

        y -= lineHeight;
      });

      y -= 6; // paragraph spacing
    };

    const divider = () => {
      y -= 10;
      page.drawLine({
        start: { x: margin, y },
        end: { x: width - margin, y },
        thickness: 1,
        color: rgb(0.7, 0.7, 0.7),
      });
      y -= 20;
    };

    // ======================
    // TITLE
    // ======================
    draw('Blockchain Suitability Assessment', 20, true);
    draw(`Date: ${new Date().toLocaleDateString()}`, 11);
    divider();

    // ======================
    // EXECUTIVE SUMMARY
    // ======================
    draw('Executive Summary', 14, true);
    draw(verdict, 12, false, rgb(0.1, 0.1, 0.6)); // Outputs the precise, descriptive core verdict
    divider();

    // ======================
    // KEY RATIONALE (FIXED: Now fully dynamic)
    // ======================
    draw('Key Rationale', 14, true);

    if (sections && sections.length > 0) {
      // Loop dynamically over the itemized pillars generated by reportBuilder
      sections.forEach((sec: { title: string; paragraphs: string[] }) => {
        draw(sec.title, 12, true);
        sec.paragraphs.forEach((p: string) => {
          draw(`• ${p}`, 11, false);
        });
        y -= 4; // Add tiny padding between sections
      });
    } else {
      // Fallback text if sections array isn't populated
      draw('Please refer to your structural input logs for architectural breakdown markers.');
    }

    divider();

    // ======================
    // USER RESPONSES
    // ======================
    draw('User Responses', 14, true);

    const formatKey = (key: string) =>
      key
        .replace(/_/g, ' ')
        .replace(/\b\w/g, (c) => c.toUpperCase());

    Object.entries(answers).forEach(([key, value]) => {
      draw(`${formatKey(key)}: ${String(value).toUpperCase()}`);
    });

    divider();

    draw(
      'This report was generated using the Blockchain Suitability Assessment Framework.',
      9
    );

    // ======================
    // FINAL SAFE RETURN (Vercel Fix)
    // ======================
    const pdfBytes = await pdf.save();

    const arrayBuffer = new ArrayBuffer(pdfBytes.length);
    const view = new Uint8Array(arrayBuffer);
    view.set(pdfBytes);

    return new Response(arrayBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition':
          'attachment; filename="Blockchain_Assessment_Report.pdf"',
      },
    });

  } catch (error) {
    console.error('PDF generation error:', error);
    return new Response('Error generating PDF', { status: 500 });
  }
}